name              'php-fpm'
maintainer        'ClickDiscover'
maintainer_email  'maintainer@clickdiscover.io'
license           'Unknown'
description       'Configures PHP-FPM'
version           '0.8'
recipe            'php-fpm', 'Configures PHP-FPM'
recipe            'php-fpm::collectd', 'Configures collectd for PHP-FPM'
depends           'collectd'
