default[:centrifuge][:ttl] = 3600
default[:centrifuge][:env] = 'production'
default[:centrifuge][:pdo_url] = 'pgsql:host=localhost;dbname=rotator;port=5432;user=rotator'
default[:centrifuge][:log_level] = 'Monolog\Logger::INFO'
default[:centrifuge][:fallback_lander] = 1
default[:centrifuge][:click_method] = 'direct'
default[:centrifuge][:click_url] = '"base2.php"'
default[:centrifuge][:click_url] = '"base2.php"'
default[:centrifuge][:enable_lander_tracking] = true
