name              'deploy'
maintainer        'FlagshipPromotions'
maintainer_email  'maintainer@flagshoppromotions.com'
license           'Unknown'
description       'Deploys apps'
version           '0.1.0'
recipe            'deploy', 'Deploys apps'
depends           'scm_helper'
