name              'configure_nginx'
maintainer        'FlagshipPromotions'
maintainer_email  'maintainer@flagshoppromotions.com'
license           'Unknown'
description       'Configures nginx'
version           '0.0.2'
depends           'sslmate'
recipe            'configure_nginx', 'Configures nginx'
