name              'nginx'
maintainer        'ClickDiscover'
maintainer_email  'maintainer@clickdiscover.io'
license           'Unknown'
description       'Configures nginx'
version           '0.6'
recipe            'nginx', 'Configures nginx without SSL'
recipe            'nginx::ssl', 'Configures nginx with SSL'
recipe            'nginx::collectd', 'Configures collectd with nginx'
depends           'route53'
depends           'sslmate'
depends           'collectd'
depends           'htpasswd'
