name              'collectd'
maintainer        'ClickDiscover'
maintainer_email  'maintainer@clickdiscover.io'
license           'Unknown'
description       'Configures collectd'
version           '0.4.0'
recipe            'collectd', 'Installs and configures collectd'
