name              'cloaker'
maintainer        'FlagshipPromotions'
maintainer_email  'maintainer@flagshoppromotions.com'
license           'Unknown'
description       'Deploys third-party cloaker php file through local REST service'
version           '0.2.0'
recipe            'cloaker', 'Deploy cloaker file'
recipe            'cloaker::setup', 'Prepare www root for cloaker'
recipe            'cloaker::site_mirror', 'Create mirror of site using wget'
