name              'route53'
maintainer        'ClickDiscover'
maintainer_email  'maintainer@clickdiscover.io'
license           'Unknown'
description       'Manages Route53'
version           '0.1.0'
recipe            'route53', 'Manages'
