name              'statsd'
maintainer        'ClickDiscover'
maintainer_email  'maintainer@clickdiscover.io'
license           'Unknown'
description       'Configures statsd'
version           '0.5'
recipe            'statsd', 'Configures statsd with librato'
depends           'nodejs'
depends           'git'
