name              'statsd'
maintainer        'FlagshipPromotions'
maintainer_email  'maintainer@flagshoppromotions.com'
license           'Unknown'
description       'Configures statsd'
version           '0.5'
recipe            'statsd', 'Configures statsd with librato'
depends           'nodejs'
depends           'git'
