name              'sslmate'
maintainer        'ClickDiscover'
maintainer_email  'maintainer@clickdiscover.io'
license           'Unknown'
description       'Issues SSL certs using sslmate'
version           '0.0.2'
recipe            'sslmate', 'Issues SSL certs'
depends           'route53'
