name              'sslmate'
maintainer        'FlagshipPromotions'
maintainer_email  'maintainer@flagshoppromotions.com'
license           'Unknown'
description       'Issues SSL certs using sslmate'
version           '0.0.1'
recipe            'sslmate', 'Issues SSL certs'
